main = ".open-next/worker.js"
name = "townofus-pl"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat"]
account_id = "d1287f321cc95882fc773ab71241b51a"

workers_dev = false
route = { pattern = "townofus.pl", custom_domain = true }

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

# Environment variables for production
# Note: API credentials are set as secrets via wrangler secret put
[vars]

[[d1_databases]]
binding = "DB"
database_name = "townofus-pl"
database_id = "b1b51296-d5f7-4dd5-8c56-8a78b75c79a9"
preview_database_id = "0de6283b-a8fe-4f94-aadb-059e0def3b42"
migrations_dir = "prisma/migrations"
