main = ".open-next/worker.js"
name = "townofus-pl"
compatibility_date = "2025-07-21"
compatibility_flags = ["nodejs_compat"]
account_id = "d1287f321cc95882fc773ab71241b51a"

workers_dev = false
route = { pattern = "townofus.pl", custom_domain = true }

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

# Environment variables for production
[vars]
API_USERNAME = "${API_USERNAME}"
API_PASSWORD = "${API_PASSWORD}"

[[d1_databases]]
binding = "DB"
database_name = "townofus-pl"
database_id = "7d2708a2-98e6-43a1-a2c8-42d603e44459"
preview_database_id = "0de6283b-a8fe-4f94-aadb-059e0def3b42"
migrations_dir = "prisma/migrations"
