main = ".open-next/worker.js"
name = "townofus-pl"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat"]
account_id = "d1287f321cc95882fc773ab71241b51a"

workers_dev = false
route = { pattern = "townofus.pl", custom_domain = true }

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "townofus-pl"
database_id = "0edadde7-395f-4e3c-a69d-7d40ece774ad"
preview_database_id = "44f0d77c-c0b4-43d1-b3a3-7777be86d5d6"
migrations_dir = "prisma/migrations"
