export enum RoleSubgroups {
    Afterlife = 'afterlife',
    Investigative = 'investigative',
    Killing = 'killing',
    Power = 'power',
    Protective = 'protective',
    Support = 'support',
    Concealing = 'concealing',
    Benign = 'benign',
    Evil = 'evil',
    Outlier = 'outlier',
    Alliance = 'alliance',
    CrewmateModifier = 'crewmate',
    ImpostorModifier = 'impostor',
    UniversalModifier = 'universal',
    Unknown = 'unknown',
}

export const roleSubgroupLabels: Record<RoleSubgroups, string> = {
    [RoleSubgroups.Afterlife]: 'Pośmiertne',
    [RoleSubgroups.Investigative]: 'Śledcze',
    [RoleSubgroups.Killing]: 'Zabójcze',
    [RoleSubgroups.Power]: 'Moc',
    [RoleSubgroups.Protective]: 'Ochronne',
    [RoleSubgroups.Support]: 'Wsparcie',
    [RoleSubgroups.Concealing]: 'Ukrywające',
    [RoleSubgroups.Benign]: 'Łagodne',
    [RoleSubgroups.Evil]: 'Złe',
    [RoleSubgroups.Outlier]: 'Niestandardowe',
    [RoleSubgroups.Alliance]: 'Sojusz',
    [RoleSubgroups.CrewmateModifier]: 'Załoga',
    [RoleSubgroups.ImpostorModifier]: 'Impostor',
    [RoleSubgroups.UniversalModifier]: 'Uniwersalne',
    [RoleSubgroups.Unknown]: '[???]',
};
