// GENERATED by scripts/generate-mira-settings.ts — do not edit by hand.
// Read from the TOU-Mira submodule's tag, so it always names the build these role
// settings were derived from and the one /do_pobrania links.

export const MIRA_VERSION = '1.7.3';

/** Upstream releases. townofus-pl/TOU-Mira is a fork and publishes none of its own. */
export const MIRA_RELEASE_URL = `https://github.com/AU-Avengers/TOU-Mira/releases/tag/${MIRA_VERSION}`;

export function miraDownloadUrl(asset: string): string {
    return `https://github.com/AU-Avengers/TOU-Mira/releases/download/${MIRA_VERSION}/${asset}`;
}
