// GENERATED by scripts/generate-mira-settings.ts — do not edit by hand.
// Re-run it after bumping the TOU-Mira submodule; the submodule is synced manually.
//
// Maps each TOU-Mira role to the settings it declares: the .cfg key (the C# property name) and
// the English label (from Locale/en_US.xml, via the locale key in the option attribute). Derived
// rather than transcribed — the hand-written labels in src/mira/roles had already drifted from
// the source. See #317.

export interface MiraRoleSetting {
    /** Key as it appears in a BepInEx .cfg. */
    cfgKey: string;
    label: string;
}

export const MIRA_ROLE_SETTINGS: Readonly<Record<string, readonly MiraRoleSetting[]>> = {
    "Altruist": [
        {
            "cfgKey": "ReviveMode",
            "label": "Revive Type"
        },
        {
            "cfgKey": "ReviveRange",
            "label": "Revive Range"
        },
        {
            "cfgKey": "ReviveDuration",
            "label": "Revive Duration"
        },
        {
            "cfgKey": "MaxRevives",
            "label": "Revive Uses"
        },
        {
            "cfgKey": "KillOnStartRevive",
            "label": "Kill Altruist When Starting Revive"
        },
        {
            "cfgKey": "FreezeDuringRevive",
            "label": "Freeze Altruist During Revive"
        },
        {
            "cfgKey": "HideAtBeginningOfRevive",
            "label": "Hide Bodies at Beginning Of Revive"
        },
        {
            "cfgKey": "KillersAlertedAtStart",
            "label": "Killers Alerted Before Revive"
        },
        {
            "cfgKey": "KillersAlertedAtEnd",
            "label": "Killers Alerted After Revive"
        }
    ],
    "Ambassador": [
        {
            "cfgKey": "MaxRetrains",
            "label": "Max Retrains Available"
        },
        {
            "cfgKey": "RetrainConfirmation",
            "label": "Retrain Requires Confirmation"
        },
        {
            "cfgKey": "KillsNeeded",
            "label": "Kills Needed By Ambassador Or Teammate To Retrain"
        },
        {
            "cfgKey": "RoundWhenAvailable",
            "label": "Round In Which Retraining Is Possible"
        },
        {
            "cfgKey": "RoundCooldown",
            "label": "Rounds Needed To Retrain Again"
        }
    ],
    "Ambusher": [
        {
            "cfgKey": "MaxAmbushes",
            "label": "Ambush Uses Per Game"
        },
        {
            "cfgKey": "AmbushCooldown",
            "label": "Ambush Cooldown"
        },
        {
            "cfgKey": "UpdateInterval",
            "label": "Pursue Arrow Update Interval"
        },
        {
            "cfgKey": "ResetAmbush",
            "label": "Stop Pursuing Player On Ambush"
        },
        {
            "cfgKey": "CanVent",
            "label": "Ambusher Can Vent"
        }
    ],
    "Amnesiac": [
        {
            "cfgKey": "InheritFactionModifier",
            "label": "Inherit Faction Modifiers"
        },
        {
            "cfgKey": "RememberArrows",
            "label": "Show Arrows Pointing To Dead Bodies"
        },
        {
            "cfgKey": "RememberArrowDelay",
            "label": "Time After Death Arrow Appears"
        }
    ],
    "Arsonist": [
        {
            "cfgKey": "DouseCooldown",
            "label": "Douse Cooldown"
        },
        {
            "cfgKey": "DouseInteractions",
            "label": "Douse From Interactions"
        },
        {
            "cfgKey": "LegacyArsonist",
            "label": "Legacy Mode (No Radius)"
        },
        {
            "cfgKey": "CanVent",
            "label": "Arsonist Can Vent"
        },
        {
            "cfgKey": "ImpostorVision",
            "label": "Has Impostor Vision"
        },
        {
            "cfgKey": "DouseUses",
            "label": "Douses Possible at Once"
        },
        {
            "cfgKey": "IgniteRadius",
            "label": "Ignite Radius"
        }
    ],
    "Aurial": [
        {
            "cfgKey": "AuraInnerRadius",
            "label": "Radiate Color Range"
        },
        {
            "cfgKey": "AuraOuterRadius",
            "label": "Radiate Max Range"
        },
        {
            "cfgKey": "SenseDuration",
            "label": "Sense Duration"
        }
    ],
    "Barkeeper": [
        {
            "cfgKey": "RoleblockCooldown",
            "label": "Roleblock Cooldown"
        },
        {
            "cfgKey": "RoleblockDelayMin",
            "label": "Minimum Roleblock Delay"
        },
        {
            "cfgKey": "RoleblockDelayMax",
            "label": "Maximum Roleblock Delay"
        },
        {
            "cfgKey": "SpillDelay",
            "label": "Spill Settle Delay"
        },
        {
            "cfgKey": "SpillBuffDuration",
            "label": "Time Before Spill Slows Players Down"
        },
        {
            "cfgKey": "SpillCleanUpDuration",
            "label": "Additional Time For Spill To Be Removed"
        },
        {
            "cfgKey": "SpillEffectDuration",
            "label": "Amount of Time Player is Affected By Spill"
        },
        {
            "cfgKey": "SpillEffectBuffMultiplier",
            "label": "Spill Speed Buff Multiplier"
        },
        {
            "cfgKey": "SpillEffectDebuffMultiplier",
            "label": "Spill Speed Debuff Multiplier"
        }
    ],
    "Blackmailer": [
        {
            "cfgKey": "MaxBlackmails",
            "label": "Number Of Blackmail Uses Per Game"
        },
        {
            "cfgKey": "BlackmailCooldown",
            "label": "Blackmail Cooldown"
        },
        {
            "cfgKey": "MaxAliveForVoting",
            "label": "Max Players Alive To Allow Voting"
        },
        {
            "cfgKey": "BlackmailInARow",
            "label": "Blackmail Same Person Twice In A Row"
        },
        {
            "cfgKey": "OnlyTargetSeesBlackmail",
            "label": "Only Target Sees Blackmail"
        },
        {
            "cfgKey": "BlackmailerKill",
            "label": "Blackmailer Can Kill With Teammate"
        }
    ],
    "Bomber": [
        {
            "cfgKey": "MaxBombs",
            "label": "Bomb Uses Per Game"
        },
        {
            "cfgKey": "DetonateDelay",
            "label": "Detonate Delay"
        },
        {
            "cfgKey": "DetonateRadius",
            "label": "Detonate Radius"
        },
        {
            "cfgKey": "MaxKillsInDetonation",
            "label": "Max Kills In Detonation"
        },
        {
            "cfgKey": "AllImpsSeeBomb",
            "label": "All Impostors See Bomb"
        },
        {
            "cfgKey": "CanBombFirstRound",
            "label": "Allow Bombing in First Round"
        },
        {
            "cfgKey": "CanVent",
            "label": "Bomber Can Vent"
        }
    ],
    "Bootlegger": [
        {
            "cfgKey": "RoleblockCooldown",
            "label": "Roleblock Cooldown"
        },
        {
            "cfgKey": "RoleblockDelayMin",
            "label": "Minimum Roleblock Delay"
        },
        {
            "cfgKey": "RoleblockDelayMax",
            "label": "Maximum Roleblock Delay"
        },
        {
            "cfgKey": "PoisonRoleblockTrigger",
            "label": "Poison Triggers On"
        },
        {
            "cfgKey": "ForcedPoisonDelay",
            "label": "Poison Delay"
        }
    ],
    "Chef": [
        {
            "cfgKey": "CookCooldown",
            "label": "Cook Cooldown"
        },
        {
            "cfgKey": "ServeCooldown",
            "label": "Serve Cooldown"
        },
        {
            "cfgKey": "ResetCooldowns",
            "label": "Reset Cook [and] Serve Cooldowns Together"
        },
        {
            "cfgKey": "ServingsNeeded",
            "label": "Amount Of Servings Needed"
        },
        {
            "cfgKey": "ChefArrows",
            "label": "Show Arrows Pointing To Dead Bodies"
        },
        {
            "cfgKey": "ChefAnonymizeWin",
            "label": "Hide Role On Win Notification"
        },
        {
            "cfgKey": "SideEffectDuration",
            "label": "Duration of Side Effects"
        },
        {
            "cfgKey": "ChefArrowDelay",
            "label": "Dead Body Arrow Delay"
        },
        {
            "cfgKey": "ChefArrowDuration",
            "label": "Dead Body Arrow Duration"
        }
    ],
    "Cleric": [
        {
            "cfgKey": "BarrierCooldown",
            "label": "Barrier Cooldown"
        },
        {
            "cfgKey": "BarrierDuration",
            "label": "Barrier Duration"
        },
        {
            "cfgKey": "CleanseCooldown",
            "label": "Cleanse Cooldown"
        },
        {
            "cfgKey": "ShowBarrier",
            "label": "Protected Player Sees Barrier"
        },
        {
            "cfgKey": "AttackNotif",
            "label": "Cleric Gets Attack Notification"
        }
    ],
    "Deputy": [
        {
            "cfgKey": "WarnKiller",
            "label": "Warn Killer Upon Killing Camped Target"
        },
        {
            "cfgKey": "RevealDeputyUponShot",
            "label": "Reveal Deputy Upon Successful Shot"
        }
    ],
    "Doomsayer": [
        {
            "cfgKey": "ObserveCooldown",
            "label": "Observe Cooldown"
        },
        {
            "cfgKey": "DoomsayerGuessesToWin",
            "label": "Number Of Guesses Needed To Win"
        },
        {
            "cfgKey": "DoomGuessInvest",
            "label": "Doomsayer Can Guess Crew Investigative Roles"
        },
        {
            "cfgKey": "DoomsayerGuessAllAtOnce",
            "label": "Doomsayer Guesses All Roles At Once"
        },
        {
            "cfgKey": "CantObserve",
            "label": "Doomsayer Can't Observe"
        },
        {
            "cfgKey": "DoomWin",
            "label": "Doomsayer Win"
        },
        {
            "cfgKey": "DoomsayerKillOnlyLast",
            "label": "Kill Only The Last Victim"
        },
        {
            "cfgKey": "DoomAnonymizeWin",
            "label": "Hide Role On Win Notification"
        },
        {
            "cfgKey": "DoomContinuesGame",
            "label": "Doomsayer Continues The Game"
        }
    ],
    "Eclipsal": [
        {
            "cfgKey": "BlindCooldown",
            "label": "Blind Cooldown"
        },
        {
            "cfgKey": "BlindDuration",
            "label": "Blind Duration"
        },
        {
            "cfgKey": "BlindRadius",
            "label": "Blind Radius"
        }
    ],
    "EngineerTou": [
        {
            "cfgKey": "VentCooldown",
            "label": "Vent Cooldown"
        },
        {
            "cfgKey": "VentDuration",
            "label": "Vent Duration"
        },
        {
            "cfgKey": "MaxVents",
            "label": "Vent Uses Per Game"
        },
        {
            "cfgKey": "VentPerTasks",
            "label": "Tasks Required For Additional Vent Use"
        },
        {
            "cfgKey": "MaxFixes",
            "label": "Fix Uses Per Game"
        },
        {
            "cfgKey": "FixPerTasks",
            "label": "Tasks Required For Additional Fix Use"
        },
        {
            "cfgKey": "FixDelay",
            "label": "Fix Delay"
        }
    ],
    "Escapist": [
        {
            "cfgKey": "MaxEscapes",
            "label": "Recall Uses Per Game"
        },
        {
            "cfgKey": "RecallCooldown",
            "label": "Recall Cooldown"
        },
        {
            "cfgKey": "CanVent",
            "label": "Escapist Can Vent"
        }
    ],
    "Executioner": [
        {
            "cfgKey": "OnTargetDeath",
            "label": "On Target Death, Executioner Becomes"
        },
        {
            "cfgKey": "CanButton",
            "label": "Executioner Can Button"
        },
        {
            "cfgKey": "ExeWin",
            "label": "Executioner Win"
        },
        {
            "cfgKey": "ExeAnonymizeWin",
            "label": "Hide Role On Win Notification"
        }
    ],
    "Fairy": [
        {
            "cfgKey": "ProtectCooldown",
            "label": "Protect Cooldown"
        },
        {
            "cfgKey": "ProtectDuration",
            "label": "Protect Duration"
        },
        {
            "cfgKey": "MaxProtects",
            "label": "Max Number Of Protects"
        },
        {
            "cfgKey": "ShowProtect",
            "label": "Show Protected Player"
        },
        {
            "cfgKey": "OnTargetDeath",
            "label": "On Target Death, Fairy Becomes"
        },
        {
            "cfgKey": "FairyTargetKnows",
            "label": "Target Knows Fairy Exists"
        },
        {
            "cfgKey": "FairyKnowsTargetRole",
            "label": "Fairy Knows Target's Role"
        },
        {
            "cfgKey": "EvilTargetPercent",
            "label": "Odds Of Target Being Evil"
        }
    ],
    "Forensic": [
        {
            "cfgKey": "ExamineCooldown",
            "label": "Examine Cooldown"
        },
        {
            "cfgKey": "ForensicReportOn",
            "label": "Show Forensic Reports"
        },
        {
            "cfgKey": "ForensicRoleDuration",
            "label": "Time Where Forensic Will Have Role"
        },
        {
            "cfgKey": "ForensicFactionDuration",
            "label": "Time Where Forensic Will Have Faction"
        }
    ],
    "Glitch": [
        {
            "cfgKey": "KillCooldown",
            "label": "Kill Cooldown"
        },
        {
            "cfgKey": "MimicCooldown",
            "label": "Mimic Cooldown"
        },
        {
            "cfgKey": "MimicDuration",
            "label": "Mimic Duration"
        },
        {
            "cfgKey": "MoveWithMenu",
            "label": "Move While Using Mimic Menu (KB ONLY)"
        },
        {
            "cfgKey": "HackCooldown",
            "label": "Hack Cooldown"
        },
        {
            "cfgKey": "HackDuration",
            "label": "Hack Duration"
        },
        {
            "cfgKey": "CanVent",
            "label": "Glitch Can Vent"
        }
    ],
    "Grenadier": [
        {
            "cfgKey": "MaxFlashes",
            "label": "Flash Uses Per Game"
        },
        {
            "cfgKey": "GrenadeCooldown",
            "label": "Flash Grenade Cooldown"
        },
        {
            "cfgKey": "GrenadeDuration",
            "label": "Flash Grenade Duration"
        },
        {
            "cfgKey": "FlashRadius",
            "label": "Flash Radius"
        },
        {
            "cfgKey": "SabotageFlashing",
            "label": "Allow Flashing During Sabotage"
        },
        {
            "cfgKey": "CanVent",
            "label": "Grenadier Can Vent"
        }
    ],
    "Haunter": [
        {
            "cfgKey": "NumTasksLeftBeforeClickable",
            "label": "Tasks Left Before Clickable"
        },
        {
            "cfgKey": "NumTasksLeftBeforeAlerted",
            "label": "Tasks Left Before Alerted"
        },
        {
            "cfgKey": "RevealNeutralRoles",
            "label": "Reveal Neutral Roles"
        },
        {
            "cfgKey": "HaunterCanBeClickedBy",
            "label": "Can Be Clicked By"
        }
    ],
    "Herbalist": [
        {
            "cfgKey": "HerbCooldown",
            "label": "Herb Cooldown"
        },
        {
            "cfgKey": "ConfuseDelay",
            "label": "Confuse Delay"
        },
        {
            "cfgKey": "ConfuseDuration",
            "label": "Confuse Duration"
        },
        {
            "cfgKey": "GlamourDuration",
            "label": "Glamour Duration"
        },
        {
            "cfgKey": "ProtectDuration",
            "label": "Protect Duration"
        },
        {
            "cfgKey": "ShowBarrier",
            "label": "Protected Player Sees Barrier"
        },
        {
            "cfgKey": "AttackNotif",
            "label": "Notify Herbalist Upon Attack"
        },
        {
            "cfgKey": "MaxExposeUses",
            "label": "Max Expose Uses"
        },
        {
            "cfgKey": "MaxConfuseUses",
            "label": "Max Confuse Uses"
        },
        {
            "cfgKey": "MaxProtectUses",
            "label": "Max Protect Uses"
        }
    ],
    "HnsCamouflager": [
        {
            "cfgKey": "MaxCamoUses",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.CamouflagerCamoUses"
        },
        {
            "cfgKey": "CamoCooldown",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.CamouflagerCamoCooldown"
        },
        {
            "cfgKey": "CamoDuration",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.CamouflagerCamoDuration"
        },
        {
            "cfgKey": "CamoDisablesProxBar",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.CamouflagerCamoDisablesProxBar"
        }
    ],
    "HnsChameleon": [
        {
            "cfgKey": "MaxSwoops",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.ChameleonSwoopUsesPerRound"
        },
        {
            "cfgKey": "SwoopCooldown",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.ChameleonSwoopCooldown"
        },
        {
            "cfgKey": "SwoopDuration",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.ChameleonSwoopDuration"
        },
        {
            "cfgKey": "CanVent",
            "label": "Swooper Can Vent"
        }
    ],
    "HnsMystic": [
        {
            "cfgKey": "MysticArrowDuration",
            "label": "TownOfUsMira.HideAndSeek.Modifier.Option.MysticDeadBodyArrowDuration"
        }
    ],
    "HnsSnitch": [
        {
            "cfgKey": "CommonTaskMultiplier",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.SnitchCommonTaskMultiplier"
        },
        {
            "cfgKey": "ShortTaskMultiplier",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.SnitchShortTaskMultiplier"
        },
        {
            "cfgKey": "LongTaskMultiplier",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.SnitchLongTaskMultiplier"
        },
        {
            "cfgKey": "SnitchNotifyDuration",
            "label": "TownOfUsMira.HideAndSeek.Role.Option.SnitchNotifyDuration"
        }
    ],
    "Hunter": [
        {
            "cfgKey": "HunterKillCooldown",
            "label": "Hunter Kill Cooldown"
        },
        {
            "cfgKey": "HunterStalkCooldown",
            "label": "Hunter Stalk Cooldown"
        },
        {
            "cfgKey": "HunterStalkDuration",
            "label": "Hunter Stalk Duration"
        },
        {
            "cfgKey": "RetributionOnVote",
            "label": "Hunter Kills Last Voter If Voted Out"
        },
        {
            "cfgKey": "HunterBodyReport",
            "label": "Hunter Can Report Who They've Killed"
        },
        {
            "cfgKey": "StalkUses",
            "label": "Initial Stalk Uses"
        },
        {
            "cfgKey": "StalkPerTasks",
            "label": "Tasks Required For Additional Stalk Use"
        },
        {
            "cfgKey": "StalkTriggeredBy",
            "label": "Stalk Triggered By"
        },
        {
            "cfgKey": "SeesTypeOfInteraction",
            "label": "Hunter Sees Interaction Type"
        }
    ],
    "Hypnotist": [
        {
            "cfgKey": "HypnotiseCooldown",
            "label": "Hypnotize Cooldown"
        },
        {
            "cfgKey": "HypnoKill",
            "label": "Hypnotist Can Kill With Teammate"
        }
    ],
    "Imitator": [
        {
            "cfgKey": "ImitateNeutrals",
            "label": "Imitate Neutral Counterparts"
        },
        {
            "cfgKey": "ImitateImpostors",
            "label": "Imitate Impostor Counterparts"
        },
        {
            "cfgKey": "ImitateBasicCrewmate",
            "label": "Imitate Basic Crewmate"
        },
        {
            "cfgKey": "ImitatorGuess",
            "label": "Imitator Must Be Guessed As"
        }
    ],
    "Inquisitor": [
        {
            "cfgKey": "VanquishCooldown",
            "label": "Vanquish Cooldown"
        },
        {
            "cfgKey": "FirstRoundUse",
            "label": "Allow Vanquish in First Round"
        },
        {
            "cfgKey": "StallGame",
            "label": "Inquisitor Continues Game In Final 3"
        },
        {
            "cfgKey": "CantInquire",
            "label": "Inquisitor Can't Inquire"
        },
        {
            "cfgKey": "InquisAnonymizeWin",
            "label": "Hide Role On Win Notification"
        },
        {
            "cfgKey": "InquireCooldown",
            "label": "Inquire Cooldown"
        },
        {
            "cfgKey": "MaxUses",
            "label": "Max Number Of Inquiries"
        },
        {
            "cfgKey": "AmountOfHeretics",
            "label": "Amount Of Heretics Needed"
        }
    ],
    "Investigator": [
        {
            "cfgKey": "FootprintSize",
            "label": "Footprint Size"
        },
        {
            "cfgKey": "FootprintDuration",
            "label": "Footprint Duration"
        },
        {
            "cfgKey": "ShowAnonymousFootprints",
            "label": "Anonymous Footprint"
        },
        {
            "cfgKey": "ShowFootprintVent",
            "label": "Footprint Vent Visible"
        },
        {
            "cfgKey": "FootprintMode",
            "label": "Footprints Added Based On"
        },
        {
            "cfgKey": "FootprintIntervalDistance",
            "label": "Footprint Interval"
        },
        {
            "cfgKey": "FootprintIntervalTime",
            "label": "Footprint Interval"
        }
    ],
    "Jailor": [
        {
            "cfgKey": "JailCooldown",
            "label": "Jail Cooldown"
        },
        {
            "cfgKey": "MaxExecutes",
            "label": "Max Number Of Executes"
        },
        {
            "cfgKey": "JailInARow",
            "label": "Jail Same Person Twice In A Row"
        },
        {
            "cfgKey": "JaileePublicChat",
            "label": "Jailee Can Use Public Chat"
        }
    ],
    "Janitor": [
        {
            "cfgKey": "MaxClean",
            "label": "Clean Uses Per Game"
        },
        {
            "cfgKey": "CleanCooldown",
            "label": "Clean Cooldown"
        },
        {
            "cfgKey": "CleanDelay",
            "label": "Clean Delay"
        },
        {
            "cfgKey": "CooldownSync",
            "label": "Reset Kill & Clean Cooldowns Together"
        },
        {
            "cfgKey": "JanitorKill",
            "label": "Janitor Can Kill With Teammate"
        }
    ],
    "Jester": [
        {
            "cfgKey": "CanButton",
            "label": "Can Use Button"
        },
        {
            "cfgKey": "ImpostorVision",
            "label": "Has Impostor Vision"
        },
        {
            "cfgKey": "JestWin",
            "label": "After Win Type"
        },
        {
            "cfgKey": "CanVent",
            "label": "Can Hide In Vents"
        },
        {
            "cfgKey": "VentCooldown",
            "label": "Vent Cooldown"
        },
        {
            "cfgKey": "VentDuration",
            "label": "Vent Duration"
        },
        {
            "cfgKey": "CanPoke",
            "label": "Can Poke Others"
        },
        {
            "cfgKey": "PokeCooldown",
            "label": "Poke Cooldown"
        },
        {
            "cfgKey": "ScatterOn",
            "label": "Scatter Mechanic Enabled"
        },
        {
            "cfgKey": "ScatterTimer",
            "label": "Scatter Timer"
        },
        {
            "cfgKey": "JestAnnounceWin",
            "label": "Notify Others On Win"
        }
    ],
    "Juggernaut": [
        {
            "cfgKey": "KillCooldown",
            "label": "Initial Kill Cooldown"
        },
        {
            "cfgKey": "CanVent",
            "label": "Juggernaut Can Vent"
        },
        {
            "cfgKey": "KillCooldownReduction",
            "label": "Kill Cooldown Reduction"
        }
    ],
    "Lookout": [
        {
            "cfgKey": "WatchCooldown",
            "label": "Watch Cooldown"
        },
        {
            "cfgKey": "MaxWatches",
            "label": "Initial Players That Can be Watched"
        },
        {
            "cfgKey": "LoResetOnNewRound",
            "label": "Lookout Watches Reset After Each Round"
        },
        {
            "cfgKey": "WatchType",
            "label": "Watched Player Feedback Reveals"
        },
        {
            "cfgKey": "LookoutSeesIndirectAttacks",
            "label": "See Indirect Attacks"
        },
        {
            "cfgKey": "TaskUses",
            "label": "Get More Uses From Completing Tasks"
        }
    ],
    "Medic": [
        {
            "cfgKey": "ShowShielded",
            "label": "Show Shielded Player"
        },
        {
            "cfgKey": "WhoGetsNotification",
            "label": "Who Gets Murder Attempt Indicator"
        },
        {
            "cfgKey": "ChangeTarget",
            "label": "Can Give Shield Away Next Round"
        },
        {
            "cfgKey": "ShieldBreaks",
            "label": "Shield Breaks On Murder Attempt"
        },
        {
            "cfgKey": "ShowReports",
            "label": "Show Reports in Chat"
        },
        {
            "cfgKey": "MedicShieldUses",
            "label": "Max Amount of Shield Uses"
        },
        {
            "cfgKey": "MedicReportNameDuration",
            "label": "Time Where Medic Will Have Name"
        },
        {
            "cfgKey": "MedicReportColorDuration",
            "label": "Time Where Medic Will Have Color Type"
        }
    ],
    "Medium": [
        {
            "cfgKey": "MediateCooldown",
            "label": "Mediate Cooldown"
        },
        {
            "cfgKey": "MediateDuration",
            "label": "Mediate Duration"
        },
        {
            "cfgKey": "MediatingSpeed",
            "label": "Spirit Speed When Mediating"
        },
        {
            "cfgKey": "LivingSeeSpiritTimer",
            "label": "Time Before Spirit is Visible to Others"
        },
        {
            "cfgKey": "PlayerVisibility",
            "label": "Medium can Identify"
        },
        {
            "cfgKey": "ArrowVisibility",
            "label": "Arrow Visibility"
        },
        {
            "cfgKey": "WhoIsRevealed",
            "label": "Who is Revealed"
        }
    ],
    "Medusa": [
        {
            "cfgKey": "KillCooldown",
            "label": "Petrify Cooldown"
        },
        {
            "cfgKey": "StoneDelay",
            "label": "Time For Victim To Become Stoned"
        },
        {
            "cfgKey": "StoneCompletion",
            "label": "Time Before Stone Shatters"
        },
        {
            "cfgKey": "CanVent",
            "label": "Medusa Can Vent"
        },
        {
            "cfgKey": "StoneGazeAvailable",
            "label": "Allow Stone Gazing"
        },
        {
            "cfgKey": "StoneGazeCooldown",
            "label": "Stone Gaze Cooldown"
        },
        {
            "cfgKey": "StoneGazeDuration",
            "label": "Stone Gaze Duration"
        },
        {
            "cfgKey": "StoneGazeUses",
            "label": "Stone Gaze Uses"
        }
    ],
    "Mercenary": [
        {
            "cfgKey": "GuardCooldown",
            "label": "Guard Cooldown"
        },
        {
            "cfgKey": "MaxUses",
            "label": "Max Number Of Guards"
        },
        {
            "cfgKey": "BribeCost",
            "label": "Bribe Cost"
        },
        {
            "cfgKey": "GuardProtection",
            "label": "Guarding Stops Attacks"
        },
        {
            "cfgKey": "GoldGivenFromAttack",
            "label": "Gold Given From An Attack"
        }
    ],
    "Miner": [
        {
            "cfgKey": "MaxMines",
            "label": "Number Of Miner Vents Per Game"
        },
        {
            "cfgKey": "MineCooldown",
            "label": "Mine Cooldown"
        },
        {
            "cfgKey": "MineVisibility",
            "label": "Mine Visiblity"
        },
        {
            "cfgKey": "MinerKill",
            "label": "Miner Can Kill With Teammate"
        },
        {
            "cfgKey": "MineDelay",
            "label": "Mine Delay"
        }
    ],
    "Mirrorcaster": [
        {
            "cfgKey": "WhoGetsNotification",
            "label": "Who Gets Murder Attempt Indicator"
        },
        {
            "cfgKey": "MultiUnleash",
            "label": "Accumulate Multiple Unleashes"
        },
        {
            "cfgKey": "MaxMirrors",
            "label": "Max Number Of Magic Mirrors"
        },
        {
            "cfgKey": "AttackInformationGiven",
            "label": "Information Received Upon Attack"
        }
    ],
    "Monarch": [
        {
            "cfgKey": "KnightCooldown",
            "label": "Knight Cooldown"
        },
        {
            "cfgKey": "MaxKnights",
            "label": "Maximum Knights"
        },
        {
            "cfgKey": "VotesPerKnight",
            "label": "Votes Per Knight"
        },
        {
            "cfgKey": "KnightDelay",
            "label": "Knight Delay (Cancellable)"
        },
        {
            "cfgKey": "RevealAtMeeting",
            "label": "Reveal Knighting At Meeting"
        },
        {
            "cfgKey": "ShowKnightedVotes",
            "label": "Show Knighted Votes"
        },
        {
            "cfgKey": "FirstRoundUse",
            "label": "Allow Round One Knighting"
        },
        {
            "cfgKey": "InformWhenKnightDies",
            "label": "Inform Monarch If a Knight Dies"
        },
        {
            "cfgKey": "CrewKnightsGrantKillImmunity",
            "label": "Crew Knights Grant Kill Immunity"
        }
    ],
    "Morphling": [
        {
            "cfgKey": "MaxSamples",
            "label": "Samples Per Game"
        },
        {
            "cfgKey": "MaxMorphs",
            "label": "Morph Uses Per Round"
        },
        {
            "cfgKey": "MorphlingCooldown",
            "label": "Morph Cooldown"
        },
        {
            "cfgKey": "MorphlingDuration",
            "label": "Morph Duration"
        },
        {
            "cfgKey": "CanVent",
            "label": "Morphling Can Vent"
        }
    ],
    "Mystic": [
        {
            "cfgKey": "MysticArrowDuration",
            "label": "Dead Body Arrow Duration"
        },
        {
            "cfgKey": "MysticHnsPopUp",
            "label": "Show Death Pop-Up"
        }
    ],
    "Officer": [
        {
            "cfgKey": "ShootCooldown",
            "label": "Shoot Cooldown"
        },
        {
            "cfgKey": "LoadCooldown",
            "label": "Load Cooldown"
        },
        {
            "cfgKey": "CanSelfReport",
            "label": "Can Self Report"
        },
        {
            "cfgKey": "FirstRoundShooting",
            "label": "Allow Shooting in First Round"
        },
        {
            "cfgKey": "CanOnlyShootActiveKillers",
            "label": "Officer Can Only Shoot Players That Have Killed"
        },
        {
            "cfgKey": "CrewKillingAreInnocent",
            "label": "Crewmate Killing Roles are Innocent"
        },
        {
            "cfgKey": "NonKillingNeutralsAreInnocent",
            "label": "Non-Killing Neutrals are Innocent"
        },
        {
            "cfgKey": "MaxBulletsTotal",
            "label": "Maximum Bullets in Total"
        },
        {
            "cfgKey": "MaxBulletsAtOnce",
            "label": "Maximum Bullets at Once"
        },
        {
            "cfgKey": "RoundsPunished",
            "label": "# of Rounds to Shoot Again After Misfire"
        }
    ],
    "Oracle": [
        {
            "cfgKey": "ConfessCooldown",
            "label": "Confess Cooldown"
        },
        {
            "cfgKey": "BlessCooldown",
            "label": "Bless Cooldown"
        },
        {
            "cfgKey": "RevealAccuracyPercentage",
            "label": "Reveal Accuracy"
        },
        {
            "cfgKey": "ShowNeutralBenignAsEvil",
            "label": "Neutral Benign Show Up As Evil"
        },
        {
            "cfgKey": "ShowNeutralEvilAsEvil",
            "label": "Neutral Evils Show Up As Evil"
        },
        {
            "cfgKey": "ShowNeutralKillingAsEvil",
            "label": "Neutral Killers Show Up As Evil"
        },
        {
            "cfgKey": "ShowNeutralOutlierAsEvil",
            "label": "Neutral Outliers Show Up As Evil"
        }
    ],
    "Parasite": [
        {
            "cfgKey": "OvertakeCooldown",
            "label": "Overtake Cooldown"
        },
        {
            "cfgKey": "OvertakeKillCooldown",
            "label": "Kill Cooldown"
        },
        {
            "cfgKey": "ControlDuration",
            "label": "Control Duration"
        },
        {
            "cfgKey": "SaveVictimIfParasiteDies",
            "label": "Save Victim If Parasite Dies"
        },
        {
            "cfgKey": "SaveVictimIfMeetingCalled",
            "label": "Save Victim If Meeting Called"
        },
        {
            "cfgKey": "CanVent",
            "label": "Parasite Can Vent"
        },
        {
            "cfgKey": "CanMoveIndependently",
            "label": "Parasite Can Move Independently"
        },
        {
            "cfgKey": "OvertakenLooksLikeParasite",
            "label": "Overtaken Looks Like Parasite"
        }
    ],
    "Plaguebearer": [
        {
            "cfgKey": "PestChance",
            "label": "Instant Pestilence Chance"
        },
        {
            "cfgKey": "InfectCooldown",
            "label": "Infect Cooldown"
        },
        {
            "cfgKey": "AnnouncePest",
            "label": "Announce Pestilence Transformation"
        },
        {
            "cfgKey": "PestKillCooldown",
            "label": "Pestilence Kill Cooldown"
        },
        {
            "cfgKey": "CanVent",
            "label": "Pestilence Can Vent"
        }
    ],
    "Plumber": [
        {
            "cfgKey": "FlushCooldown",
            "label": "Flush Cooldown"
        },
        {
            "cfgKey": "FlushDuration",
            "label": "Flush Duration"
        },
        {
            "cfgKey": "BlockCooldown",
            "label": "Block Cooldown"
        },
        {
            "cfgKey": "MaxBarricades",
            "label": "Initial Number Of Barricades"
        },
        {
            "cfgKey": "BarricadeRoundDuration",
            "label": "Amount Of Rounds Barricades Last"
        },
        {
            "cfgKey": "TaskUses",
            "label": "Get More Barricades From Completing Tasks"
        }
    ],
    "Politician": [
        {
            "cfgKey": "CampaignCooldown",
            "label": "Campaign Cooldown"
        },
        {
            "cfgKey": "PreventCampaign",
            "label": "Prevent Campaigning on Failed Reveal"
        }
    ],
    "PolusSerialKiller": [
        {
            "cfgKey": "KillCooldown",
            "label": "Kill Cooldown"
        },
        {
            "cfgKey": "CooldownKillStreakReduction",
            "label": "Cooldown Reduction For Kills In A Round"
        },
        {
            "cfgKey": "MinPlayers",
            "label": "Minimum Players to Kill"
        }
    ],
    "PolusSwooper": [
        {
            "cfgKey": "SwoopCooldown",
            "label": "Swoop Cooldown"
        },
        {
            "cfgKey": "SwoopDuration",
            "label": "Swoop Duration"
        }
    ],
    "Prosecutor": [
        {
            "cfgKey": "MaxProsecutions",
            "label": "Max Prosecutions"
        },
        {
            "cfgKey": "WrongfulProsecutionResult",
            "label": "On Wrongful Prosecution"
        }
    ],
    "Puppeteer": [
        {
            "cfgKey": "ControlPerKills",
            "label": "Kills Required For Additional Control Use"
        }
    ],
    "Scavenger": [
        {
            "cfgKey": "ScavengeDuration",
            "label": "Scavenge Duration"
        },
        {
            "cfgKey": "ScavengeIncreaseDuration",
            "label": "Scavenge Duration Increase Per Kill"
        },
        {
            "cfgKey": "ScavengeCorrectKillCooldown",
            "label": "Scavenge Kill Cooldown On Correct Kill"
        },
        {
            "cfgKey": "ScavengeIncorrectKillCooldown",
            "label": "Kill Cooldown Multiplier On Incorrect Kill"
        }
    ],
    "Seer": [
        {
            "cfgKey": "SeerCooldown",
            "label": "Reveal/Compare Cooldown"
        },
        {
            "cfgKey": "MaxCompares",
            "label": "Max Uses of Reveal/Compare"
        },
        {
            "cfgKey": "SalemSeer",
            "label": "Compare Players Instead of Checking Alignments"
        },
        {
            "cfgKey": "CanUseMultiplePerRound",
            "label": "Can Reveal/Compare More Than Once Per Round"
        },
        {
            "cfgKey": "CompareEachPlayerOnce",
            "label": "Can Only Compare Each Player Once"
        },
        {
            "cfgKey": "BenignShowFriendlyToAll",
            "label": "Neutral Benign Show Friends To All"
        },
        {
            "cfgKey": "EvilShowFriendlyToAll",
            "label": "Neutral Evils Show Friends To All"
        },
        {
            "cfgKey": "OutlierShowFriendlyToAll",
            "label": "Neutral Outliers Show Friends To All"
        },
        {
            "cfgKey": "ShowCrewmateKillingAsRed",
            "label": "Crewmate Killing Roles Are Red"
        },
        {
            "cfgKey": "ShowNeutralBenignAsRed",
            "label": "Neutral Benign Roles Are Red"
        },
        {
            "cfgKey": "ShowNeutralEvilAsRed",
            "label": "Neutral Evil Roles Are Red"
        },
        {
            "cfgKey": "ShowNeutralKillingAsRed",
            "label": "Neutral Killing Roles Are Red"
        },
        {
            "cfgKey": "ShowNeutralOutlierAsRed",
            "label": "Neutral Outlier Roles Are Red"
        },
        {
            "cfgKey": "SwapTraitorColors",
            "label": "Traitor Swaps Colors"
        }
    ],
    "Sentry": [
        {
            "cfgKey": "PlacementCooldown",
            "label": "Placement Cooldown"
        },
        {
            "cfgKey": "DeployedCamerasVisibility",
            "label": "Deployed Cameras Visibility"
        },
        {
            "cfgKey": "PortableCamerasMode",
            "label": "Instant Portable Cameras (or After Tasks)"
        },
        {
            "cfgKey": "CameraRoundsLast",
            "label": "Amount Of Rounds Cameras Last"
        },
        {
            "cfgKey": "MaxCamerasPlaced",
            "label": "Max Cameras Placed At Once"
        },
        {
            "cfgKey": "PortableCamsBattery",
            "label": "Portable Cameras Battery"
        },
        {
            "cfgKey": "CamerasVisibleAfter",
            "label": "Cameras Visible After"
        },
        {
            "cfgKey": "CanMoveWhilePlacingCameras",
            "label": "Can Move While Placing Cameras"
        },
        {
            "cfgKey": "InitialCameras",
            "label": "Initial Cameras"
        },
        {
            "cfgKey": "TasksPerCamera",
            "label": "Tasks Required Per Camera"
        },
        {
            "cfgKey": "BlindspotsCount",
            "label": "Blind Spots"
        },
        {
            "cfgKey": "Blindspot1Room",
            "label": "Blindspot 1 Room"
        },
        {
            "cfgKey": "Blindspot2Room",
            "label": "Blindspot 2 Room"
        },
        {
            "cfgKey": "Blindspot3Room",
            "label": "Blindspot 3 Room"
        },
        {
            "cfgKey": "Blindspot4Room",
            "label": "Blindspot 4 Room"
        },
        {
            "cfgKey": "Blindspot5Room",
            "label": "Blindspot 5 Room"
        },
        {
            "cfgKey": "Blindspot6Room",
            "label": "Blindspot 6 Room"
        },
        {
            "cfgKey": "Blindspot7Room",
            "label": "Blindspot 7 Room"
        },
        {
            "cfgKey": "Blindspot8Room",
            "label": "Blindspot 8 Room"
        },
        {
            "cfgKey": "Blindspot9Room",
            "label": "Blindspot 9 Room"
        },
        {
            "cfgKey": "Blindspot10Room",
            "label": "Blindspot 10 Room"
        }
    ],
    "Sheriff": [
        {
            "cfgKey": "KillCooldown",
            "label": "Kill Cooldown"
        },
        {
            "cfgKey": "SheriffBodyReport",
            "label": "Can Self Report"
        },
        {
            "cfgKey": "FirstRoundUse",
            "label": "Allow Shooting in First Round"
        },
        {
            "cfgKey": "MisfireType",
            "label": "Misfire Kills"
        },
        {
            "cfgKey": "ShootNeutralBenign",
            "label": "Can Shoot Neutral Benign Roles"
        },
        {
            "cfgKey": "ShootNeutralEvil",
            "label": "Can Shoot Neutral Evil Roles"
        },
        {
            "cfgKey": "ShootNeutralKiller",
            "label": "Can Shoot Neutral Killing Roles"
        },
        {
            "cfgKey": "ShootNeutralOutlier",
            "label": "Can Shoot Neutral Outlier Roles"
        }
    ],
    "Snitch": [
        {
            "cfgKey": "SnitchNeutralRoles",
            "label": "Snitch Reveals Neutral Killers"
        },
        {
            "cfgKey": "SnitchSeesTraitor",
            "label": "Snitch Sees Traitor"
        },
        {
            "cfgKey": "SnitchSeesImpostorsMeetings",
            "label": "Snitch Sees Impostors In Meetings"
        },
        {
            "cfgKey": "TaskRemainingWhenRevealed",
            "label": "Tasks Remaining When Revealed"
        }
    ],
    "Sonar": [
        {
            "cfgKey": "TrackCooldown",
            "label": "Track Cooldown"
        },
        {
            "cfgKey": "MaxTracks",
            "label": "Initial Number Of Tracks"
        },
        {
            "cfgKey": "UpdateInterval",
            "label": "Arrow Update Interval"
        },
        {
            "cfgKey": "SoundOnDeactivate",
            "label": "Trackers Make Sound On Death"
        },
        {
            "cfgKey": "ResetOnNewRound",
            "label": "Trackers Reset After Each Round"
        },
        {
            "cfgKey": "TaskUses",
            "label": "Get More Uses From Completing Tasks"
        }
    ],
    "Spectre": [
        {
            "cfgKey": "NumTasksLeftBeforeClickable",
            "label": "Tasks Left Before Clickable"
        },
        {
            "cfgKey": "SpectreWin",
            "label": "Spectre Win"
        }
    ],
    "Spellslinger": [
        {
            "cfgKey": "HexCooldown",
            "label": "Hex Cooldown"
        },
        {
            "cfgKey": "MaxHexes",
            "label": "Max Hexes"
        },
        {
            "cfgKey": "HexBombDuration",
            "label": "Hex Bomb Countdown Duration"
        }
    ],
    "Spy": [
        {
            "cfgKey": "WhoSeesDead",
            "label": "Who Sees Dead Bodies On Admin"
        },
        {
            "cfgKey": "HasPortableAdmin",
            "label": "Allow Portable Admin Table For"
        },
        {
            "cfgKey": "MoveWithMenu",
            "label": "Move While Using Portable Admin"
        },
        {
            "cfgKey": "StartingCharge",
            "label": "Starting Charge"
        },
        {
            "cfgKey": "RoundCharge",
            "label": "Battery Charged Each Round"
        },
        {
            "cfgKey": "TaskCharge",
            "label": "Battery Charged Per Task"
        },
        {
            "cfgKey": "DisplayCooldown",
            "label": "Portable Admin Display Cooldown"
        },
        {
            "cfgKey": "DisplayDuration",
            "label": "Portable Admin Display Duration"
        }
    ],
    "Survivor": [
        {
            "cfgKey": "VestCooldown",
            "label": "Vest Cooldown"
        },
        {
            "cfgKey": "VestDuration",
            "label": "Vest Duration"
        },
        {
            "cfgKey": "MaxVests",
            "label": "Max Number Of Vests"
        },
        {
            "cfgKey": "ScatterOn",
            "label": "Survivor Scatter Mechanic Enabled"
        },
        {
            "cfgKey": "ScatterTimer",
            "label": "Survivor Scatter Timer"
        }
    ],
    "Swapper": [
        {
            "cfgKey": "CanButton",
            "label": "Can Call Button"
        }
    ],
    "Swooper": [
        {
            "cfgKey": "MaxSwoops",
            "label": "Swoop Uses Per Round"
        },
        {
            "cfgKey": "SwoopCooldown",
            "label": "Swoop Cooldown"
        },
        {
            "cfgKey": "SwoopDuration",
            "label": "Swoop Duration"
        },
        {
            "cfgKey": "TrackedMidSwoop",
            "label": "Can be Tracked while Invisible"
        },
        {
            "cfgKey": "CanVent",
            "label": "Swooper Can Vent"
        }
    ],
    "TimeLord": [
        {
            "cfgKey": "RewindCooldown",
            "label": "Rewind Cooldown"
        },
        {
            "cfgKey": "RewindDuration",
            "label": "Rewind Duration"
        },
        {
            "cfgKey": "RewindHistorySeconds",
            "label": "Rewind History"
        },
        {
            "cfgKey": "CanUseVitals",
            "label": "Can Use Vitals"
        },
        {
            "cfgKey": "UndoTasksOnRewind",
            "label": "Undo Tasks On Rewind"
        },
        {
            "cfgKey": "UncleanBodiesOnRewind",
            "label": "Unclean Bodies On Rewind"
        },
        {
            "cfgKey": "NotifyOnRevive",
            "label": "Notify Time Lord On Revive"
        },
        {
            "cfgKey": "MaxUses",
            "label": "Initial Uses"
        },
        {
            "cfgKey": "UsesPerTasks",
            "label": "Tasks Required For Additional Rewind Use"
        },
        {
            "cfgKey": "ReviveOnRewind",
            "label": "Revive On Rewind"
        }
    ],
    "Traitor": [
        {
            "cfgKey": "LatestSpawn",
            "label": "Minimum People Alive When Traitor Can Spawn"
        },
        {
            "cfgKey": "NeutralKillingStopsTraitor",
            "label": "Traitor Won't Spawn If NK Is Alive"
        },
        {
            "cfgKey": "RemoveExistingRoles",
            "label": "Disable Existing Impostor Roles"
        },
        {
            "cfgKey": "TraitorGuess",
            "label": "Traitor Must Be Guessed As"
        },
        {
            "cfgKey": "TraitorCanAssassin",
            "label": "Traitor Becomes Assassin"
        }
    ],
    "Transporter": [
        {
            "cfgKey": "TransporterCooldown",
            "label": "Transport Cooldown"
        },
        {
            "cfgKey": "MaxNumTransports",
            "label": "Initial Uses"
        },
        {
            "cfgKey": "MoveWithMenu",
            "label": "Move While Using Transport Menu (KB ONLY)"
        },
        {
            "cfgKey": "CanUseVitals",
            "label": "Can Use Vitals"
        },
        {
            "cfgKey": "TaskUses",
            "label": "Get More Uses From Completing Tasks"
        }
    ],
    "Trapper": [
        {
            "cfgKey": "TrapCooldown",
            "label": "Trap Cooldown"
        },
        {
            "cfgKey": "MinAmountOfTimeInTrap",
            "label": "Min Amount Of Time In Trap To Register"
        },
        {
            "cfgKey": "MaxTraps",
            "label": "Initial Number Of Traps"
        },
        {
            "cfgKey": "TrapSize",
            "label": "Trap Size"
        },
        {
            "cfgKey": "TrapsRemoveOnNewRound",
            "label": "Traps Reset After Each Round"
        },
        {
            "cfgKey": "MinAmountOfPlayersInTrap",
            "label": "Minimum Number Of Roles Required To Trigger Trap"
        },
        {
            "cfgKey": "TaskUses",
            "label": "Get More Uses From Completing Tasks"
        }
    ],
    "Undertaker": [
        {
            "cfgKey": "DragCooldown",
            "label": "Drag Cooldown"
        },
        {
            "cfgKey": "DragSpeedMultiplier",
            "label": "Drag Speed"
        },
        {
            "cfgKey": "AffectedSpeed",
            "label": "Dragging Speed Is Affected by Body Size"
        },
        {
            "cfgKey": "CanVent",
            "label": "Undertaker Can Vent"
        },
        {
            "cfgKey": "UndertakerKill",
            "label": "Undertaker Can Kill With Teammate"
        },
        {
            "cfgKey": "CanVentWithBody",
            "label": "Can Vent With Body"
        }
    ],
    "Vampire": [
        {
            "cfgKey": "BiteCooldown",
            "label": "Bite Cooldown"
        },
        {
            "cfgKey": "MaxVampires",
            "label": "Max Number Of Vampires Per Game"
        },
        {
            "cfgKey": "HasVision",
            "label": "Vampires Have Impostor Vision"
        },
        {
            "cfgKey": "CanGuessAsNewVamp",
            "label": "New Vampires Can Assassinate"
        },
        {
            "cfgKey": "CanConvertAsNewVamp",
            "label": "New Vampires Can Convert"
        },
        {
            "cfgKey": "CanVent",
            "label": "Vampires Can Vent"
        },
        {
            "cfgKey": "ConvertNeutralBenign",
            "label": "Can Convert Neutral Benign Roles"
        },
        {
            "cfgKey": "ConvertNeutralEvil",
            "label": "Can Convert Neutral Evil Roles"
        },
        {
            "cfgKey": "ConvertNeutralOutlier",
            "label": "Can Convert Neutral Outlier Roles"
        },
        {
            "cfgKey": "ConvertLovers",
            "label": "Can Convert Lovers"
        }
    ],
    "Venerer": [
        {
            "cfgKey": "AbilityCooldown",
            "label": "Ability Cooldown"
        },
        {
            "cfgKey": "AbilityDuration",
            "label": "Ability Duration"
        },
        {
            "cfgKey": "NumSprintSpeed",
            "label": "Sprint Speed"
        },
        {
            "cfgKey": "MinFreezeSpeed",
            "label": "Minimum Freeze Speed"
        },
        {
            "cfgKey": "FreezeRadius",
            "label": "Freeze Radius"
        }
    ],
    "Veteran": [
        {
            "cfgKey": "AlertCooldown",
            "label": "Alert Cooldown"
        },
        {
            "cfgKey": "AlertDuration",
            "label": "Alert Duration"
        },
        {
            "cfgKey": "MaxNumAlerts",
            "label": "Initial Number of Alerts"
        },
        {
            "cfgKey": "KilledOnAlert",
            "label": "Can Be Killed On Alert"
        },
        {
            "cfgKey": "TaskUses",
            "label": "Get More Uses From Completing Tasks"
        },
        {
            "cfgKey": "KnowWhenAttackedInMeeting",
            "label": "Knows When Attacked In Meeting"
        }
    ],
    "Vigilante": [
        {
            "cfgKey": "VigilanteKills",
            "label": "Number Of Guesses"
        },
        {
            "cfgKey": "VigilanteMultiKill",
            "label": "Can Guess More Than Once Per Meeting"
        },
        {
            "cfgKey": "VigilanteGuessKillerMods",
            "label": "Can Guess Killer Modifiers"
        },
        {
            "cfgKey": "VigilanteGuessAlliances",
            "label": "Can Guess Alliance Modifiers"
        },
        {
            "cfgKey": "MultiShots",
            "label": "Safe Shots Available"
        },
        {
            "cfgKey": "VigilanteGuessNeutralBenign",
            "label": "Can Guess Neutral Benign Roles"
        },
        {
            "cfgKey": "VigilanteGuessNeutralEvil",
            "label": "Can Guess Neutral Evil Roles"
        },
        {
            "cfgKey": "VigilanteGuessNeutralKilling",
            "label": "Can Guess Neutral Killing Roles"
        },
        {
            "cfgKey": "VigilanteGuessNeutralOutlier",
            "label": "Can Guess Neutral Outlier Roles"
        }
    ],
    "Warden": [
        {
            "cfgKey": "ShowFortified",
            "label": "Show Fortified Player"
        }
    ],
    "Warlock": [
        {
            "cfgKey": "ChargeTimeDuration",
            "label": "Time It Takes To Fully Charge"
        },
        {
            "cfgKey": "AddedTimeDuration",
            "label": "Time Multiplier Added Per Kill For Next Charge"
        },
        {
            "cfgKey": "DischargeTimeDuration",
            "label": "Time It Takes To Use Full Charge"
        }
    ],
    "Werewolf": [
        {
            "cfgKey": "RampageCooldown",
            "label": "Rampage Cooldown"
        },
        {
            "cfgKey": "RampageDuration",
            "label": "Rampage Duration"
        },
        {
            "cfgKey": "RampageKillCooldown",
            "label": "Rampage Kill Cooldown"
        },
        {
            "cfgKey": "CanVent",
            "label": "Werewolf Can Vent When Rampaged"
        }
    ]
};
