import {Role, RoleOrModifierTypes} from '@/constants/rolesAndModifiers';
import {ModSource} from '@/constants/modSources';
import {RoleSubgroups} from '@/constants/roleSubgroups';
import {Teams} from '@/constants/teams';
import {probabilityOfAppearing, SettingTypes} from '@/constants/settings';

export const MiraSentryAbilities = {
    Deploy: {
        name: 'Deploy (Rozstaw)',
        icon: '/images/mira/abilities/DeployButton.png',
    },
    View: {
        name: 'View (Podgląd)',
        icon: '/images/mira/abilities/CamButton.png',
    },
};

export const MiraSentry: Role = {
    type: RoleOrModifierTypes.Role,
    source: ModSource.Mira,
    subgroup: RoleSubgroups.Support,
    name: 'Sentry',
    id: 'mira_sentry',
    color: '#6496C8',
    team: Teams.Crewmate,
    icon: '/images/mira/roles/Sentry.png',
    description: 'Sentry może stawiać dodatkowe kamery na mapie, a następnie oglądać je z Security lub przez przenośne kamery.',
    settings: {
        ...probabilityOfAppearing(0),
        'Placement Cooldown': {
            value: 30,
            type: SettingTypes.Time,
        },
        'Deployed Cameras Visibility': {
            value: 'Immediately',
            type: SettingTypes.Text,
            description: {
                0: 'Immediately',
                1: 'After Meeting',
            },
        },
        'Cameras Visible After': {
            value: 3,
            type: SettingTypes.Time,
        },
        'Can Move While Placing Cameras': {
            value: false,
            type: SettingTypes.Boolean,
        },
        'Portable Cameras': {
            value: 'After Tasks',
            type: SettingTypes.Text,
            description: {
                0: 'After Tasks',
                1: 'Immediately',
                2: 'On Maps Without Cameras',
            },
        },
        'Initial Cameras': {
            value: 2,
            type: SettingTypes.Number,
        },
        'Amount Of Rounds Cameras Last': {
            value: 2,
            type: SettingTypes.Number,
        },
        'Tasks Required Per Camera': {
            value: 2,
            type: SettingTypes.Number,
        },
        'Max Cameras Placed At Once': {
            value: 4,
            type: SettingTypes.Number,
        },
        'Portable Cameras Battery': {
            value: 90,
            type: SettingTypes.Time,
        },
        'Blind Spots': {
            value: 0,
            type: SettingTypes.Number,
            description: {
                0: 'Off',
            },
        },
        'Blindspot 1 Room': {
            value: 0,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 2 Room': {
            value: 27,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 3 Room': {
            value: 2,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 4 Room': {
            value: 1,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 5 Room': {
            value: 6,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 6 Room': {
            value: 7,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 7 Room': {
            value: 11,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 8 Room': {
            value: 10,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 9 Room': {
            value: 12,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
        'Blindspot 10 Room': {
            value: 14,
            type: SettingTypes.Number,
            description: {
                0: 'Hallway',
                1: 'Storage',
                2: 'Cafeteria',
                3: 'Reactor',
                4: 'Upper Engine',
                5: 'Navigation',
                6: 'Admin',
                7: 'Electrical',
                8: 'O2',
                9: 'Shields',
                10: 'MedBay',
                11: 'Security',
                12: 'Weapons',
                13: 'Lower Engine',
                14: 'Communications',
                15: 'Ship Tasks',
                16: 'Doors',
                17: 'Sabotage',
                18: 'Decontamination',
                19: 'Launchpad',
                20: 'Locker Room',
                21: 'Laboratory',
                22: 'Balcony',
                23: 'Office',
                24: 'Greenhouse',
                25: 'Dropship',
                26: 'Decontamination',
                27: 'Outside',
                28: 'Specimen Room',
                29: 'Boiler Room',
                30: 'Vault',
                31: 'Cockpit',
                32: 'Armory',
                33: 'Kitchen',
                34: 'Viewing Deck',
                35: 'Hall of Portraits',
                36: 'Cargo Bay',
                37: 'Ventilation',
                38: 'Showers',
                39: 'Engine Room',
                40: 'Brig',
                41: 'Meeting Room',
                42: 'Records',
                43: 'Lounge',
                44: 'Gap Room',
                45: 'Main Hall',
                46: 'Medical',
                47: 'Decontamination',
                48: 'Zipline',
                49: 'Mining Pit',
                50: 'Fishing Dock',
                51: 'Rec Room',
                52: 'Lookout',
                53: 'Beach',
                54: 'Highlands',
                55: 'Jungle',
                56: 'Sleeping Quarters',
                57: 'Mushroom Mixup',
                58: 'Heli Sabotage',
            },
        },
    },
    abilities: [MiraSentryAbilities.Deploy, MiraSentryAbilities.View],
};
