/**
 * Emits a slim role index for the season-aware resolvers in
 * `src/app/dramaafera/_utils/gameUtils.ts`.
 *
 * Why generated rather than imported directly: the resolvers need four fields per role — id,
 * name, team, color — but `src/roles` (94 KB of source) and `src/mira/roles` (173 KB) also carry
 * JSX descriptions, settings and ability definitions. `gameUtils` is imported by client
 * components, so importing both registries would ship ~266 KB of source to the browser for the
 * sake of those five fields. Object properties cannot be tree-shaken away.
 *
 * Run by `npm run db:generate`, so it stays fresh alongside the Prisma client.
 */
import { writeFileSync } from 'node:fs';
import { Roles } from '../src/roles';
import { MiraRoles } from '../src/mira';

type Slim = { id: string; name: string; team: string; color: string; icon: string; subgroup: string | null };

const slim = (r: { id: string; name: string; team: string; color: string; icon: string; subgroup?: string }): Slim => ({
    id: r.id,
    name: r.name,
    team: r.team,
    color: r.color,
    // Taken from the registry rather than derived: legacy icons are snake_case under
    // /images/roles/, Mira's are PascalCase under /images/mira/roles/, and every role declares
    // its own path.
    icon: r.icon,
    // Lets callers ask "is this a killing role?" from the registry instead of hardcoding a list
    // that silently goes stale — RoleDetailContent had one missing four Mira killers. See #308.
    subgroup: r.subgroup ?? null,
});

const legacy = Roles.map(slim).sort((a, b) => a.id.localeCompare(b.id));
const mira = MiraRoles.map(slim).sort((a, b) => a.id.localeCompare(b.id));

const out = `// GENERATED by scripts/generate-role-index.ts — do not edit by hand.
// Re-run \`npm run db:generate\` after changing src/roles or src/mira/roles.
//
// Slim projection of the two role registries: the five fields the season-aware resolvers need,
// without the JSX descriptions, settings and abilities that make the full registries ~266 KB of
// source. See scripts/generate-role-index.ts for why.

export interface SlimRole {
    id: string;
    name: string;
    team: string;
    color: string;
    icon: string;
    subgroup: string | null;
}

/** Roles as they existed up to and including season 3. */
export const LEGACY_ROLE_INDEX: readonly SlimRole[] = ${JSON.stringify(legacy, null, 4)};

/** TOU-Mira roles, used from season 4 onward. */
export const MIRA_ROLE_INDEX: readonly SlimRole[] = ${JSON.stringify(mira, null, 4)};
`;

writeFileSync('src/roles/_generated/roleIndex.ts', out);
console.log(`role index written: ${legacy.length} legacy + ${mira.length} mira roles`);
