import {RoleSubgroups} from '@/constants/roleSubgroups';

export const roleSubgroupById: Record<string, RoleSubgroups> = {
    // Crewmate
    haunter: RoleSubgroups.Afterlife,
    aurial: RoleSubgroups.Investigative,
    investigator: RoleSubgroups.Investigative,
    lookout: RoleSubgroups.Investigative,
    medium: RoleSubgroups.Investigative,
    mystic: RoleSubgroups.Investigative,
    seer: RoleSubgroups.Investigative,
    snitch: RoleSubgroups.Investigative,
    spy: RoleSubgroups.Investigative,
    trapper: RoleSubgroups.Investigative,
    deputy: RoleSubgroups.Killing,
    hunter: RoleSubgroups.Killing,
    sheriff: RoleSubgroups.Killing,
    veteran: RoleSubgroups.Killing,
    vigilante: RoleSubgroups.Killing,
    jailor: RoleSubgroups.Power,
    politician: RoleSubgroups.Power,
    prosecutor: RoleSubgroups.Power,
    swapper: RoleSubgroups.Power,
    altruist: RoleSubgroups.Protective,
    cleric: RoleSubgroups.Protective,
    medic: RoleSubgroups.Protective,
    oracle: RoleSubgroups.Protective,
    warden: RoleSubgroups.Protective,
    engineer: RoleSubgroups.Support,
    imitator: RoleSubgroups.Support,
    plumber: RoleSubgroups.Support,
    transporter: RoleSubgroups.Support,

    // Impostor
    eclipsal: RoleSubgroups.Concealing,
    escapist: RoleSubgroups.Concealing,
    grenadier: RoleSubgroups.Concealing,
    morphling: RoleSubgroups.Concealing,
    swooper: RoleSubgroups.Concealing,
    venerer: RoleSubgroups.Concealing,
    bomber: RoleSubgroups.Killing,
    scavenger: RoleSubgroups.Killing,
    warlock: RoleSubgroups.Killing,
    traitor: RoleSubgroups.Power,
    blackmailer: RoleSubgroups.Support,
    hypnotist: RoleSubgroups.Support,
    janitor: RoleSubgroups.Support,
    miner: RoleSubgroups.Support,
    undertaker: RoleSubgroups.Support,

    // Neutral
    amnesiac: RoleSubgroups.Benign,
    mercenary: RoleSubgroups.Benign,
    survivor: RoleSubgroups.Benign,
    doomsayer: RoleSubgroups.Evil,
    executioner: RoleSubgroups.Evil,
    jester: RoleSubgroups.Evil,
    arsonist: RoleSubgroups.Killing,
    glitch: RoleSubgroups.Killing,
    juggernaut: RoleSubgroups.Killing,
    plaguebearer: RoleSubgroups.Killing,
    soul_collector: RoleSubgroups.Killing,
    vampire: RoleSubgroups.Killing,
    werewolf: RoleSubgroups.Killing,

    // Brak jednoznacznego dopasowania w docs
    guardian_angel: RoleSubgroups.Unknown,
    phantom: RoleSubgroups.Unknown,
    detective: RoleSubgroups.Unknown,
};
